language: node_js

node_js: lts/*

services:
  - docker

before_install:
  - docker pull node:alpine
  - docker pull postgres
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - docker-compose -f docker-compose.test.yml up --exit-code-from sut

deploy:
  - bash ./deploy.sh
