language: node_js

node_js: lts/*

services:
  - docker

before_install:
  - docker pull node:alpine
  - docker pull postgres

script:
  - docker-compose -f docker-compose.test.yml up

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info
