language: node_js

node_js: lts/*

services:
  - docker

before_install:
  - docker pull node:alpine
  - docker pull postgres

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

script:
  - docker-compose -f docker-compose.test.yml up --exit-code-from sut

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
