version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
    env_file:
      - .env
  sut:
    build:
      context: .
      dockerfile: dockerfile.test
    depends_on:
      - db
    env_file:
      - .env
    command: yarn test
