version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
    environment:
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
    env_file:
      - .env
  server:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
    depends_on:
      - db
    command: yarn dev
