version: "3"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=census
  server:
    restart: always
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
    depends_on:
      - db
