FROM node:alpine

WORKDIR /usr/app

ARG NODE_ENV=test
ENV NODE_ENV ${NODE_ENV}

COPY ./package.json ./

RUN yarn

COPY ./ ./

RUN "yarn", "dev"

CMD [ "bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info" ]